import fs from 'node:fs'
import process from 'node:process'

const server=fs.readFileSync(new URL('../server/index.mjs',import.meta.url),'utf8')
const app=fs.readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8')
const api=fs.readFileSync(new URL('../src/api.ts',import.meta.url),'utf8')
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'))
const lock=fs.readFileSync(new URL('../package-lock.json',import.meta.url),'utf8')
const checks=[]
const check=(name,condition,detail='')=>checks.push({name,pass:Boolean(condition),detail})
check('Package lock uses no internal registry',!/(packages\.applied-caas|internal\.api\.openai|packages\.hub)/.test(lock))
check('Server syntax entry exists',server.includes("app.get('/api/health'"))
check('Task endpoint enforces tasks.view',/app\.get\('\/api\/tasks', auth, permit\('tasks\.view'\)/.test(server))
check('Order detail has authorization guard',server.includes("Tidak dapat mengakses order ini"))
check('Public chat uses opaque public token',server.includes('conversationToken') && server.includes('public_token'))
check('Auth login rate limit enabled',server.includes("rateLimit('login'"))
check('Signup rate limit enabled',server.includes("rateLimit('signup'"))
check('Public chat rate limit enabled',server.includes("rateLimit('public-chat'"))
check('Checkout rate limit enabled',server.includes("rateLimit('orders'"))
check('Upload MIME validation enabled',server.includes("Format file tidak didukung"))
check('Sound backend type/size validation enabled',server.includes("Sound hanya menerima audio atau MP4") && server.includes('15*1024*1024'))
check('Payment endpoint is idempotency protected',server.includes("Order sudah dibayar"))
check('Production payment safety guard exists',server.includes("PAYMENT_MODE") && server.includes("Payment gateway webhook belum dikonfigurasi"))
check('Role delete protects assigned users',server.includes('Role masih digunakan oleh'))
check('Profile password minimum enforced',server.includes("Password minimal 8 karakter"))
check('Profile email duplicate returns conflict',server.includes("Email sudah digunakan akun lain"))
check('Editor/client assignment table exists',server.includes('CREATE TABLE IF NOT EXISTS site_assignments'))
check('Assigned client site endpoint exists',server.includes("/api/clients/:id/site"))
check('Frontend client API exists',api.includes('clientSite:') && api.includes('saveClientSite:') && api.includes('assignClient:'))
check('Template preview does not directly apply template',app.includes('setPreviewTemplate(template)'))
check('Dashboard copy link uses current origin',app.includes('navigator.clipboard?.writeText(`${window.location.origin}/${slug}`)'))
check('RSVP activity derives from timestamps',app.includes('ts>=date&&ts<next'))
check('Refresh session persistence remains implemented',app.includes("ikrarku-session-v7") && app.includes('api.me()'))
check('Password show/hide remains implemented',app.includes('showPassword') && app.includes('EyeOff'))
check('Signup confirmation password remains implemented',app.includes('passwordConfirm') && app.includes('Repeat Password'))
check('Live chat optimistic message persists while API writes',app.includes('setChatMessages(previous=>[...previous,optimistic])'))
check('Published article filtering on landing remains implemented',app.includes("article.status === 'Published'"))
check('Build version updated',pkg.version==='0.16.0',`version=${pkg.version}`)
check('Website manager groups Canvas by template instance',app.includes('buildWebsiteDesignGroups') && app.includes('templateInstanceId'))
check('Website manager renders template-level preview',app.includes('WebsiteTemplatePreview') && app.includes('Template pada website'))
check('Active client demo badge removed from Templates page',!app.includes('className="active-client-chip"'))
check('Applied template stores source metadata',app.includes('sourceTemplateId:template.id') && app.includes('sourceTemplateName:template.name'))

const failed=checks.filter(c=>!c.pass)
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} | ${c.name}${c.detail?` | ${c.detail}`:''}`)
console.log(`\nStatic QA: ${checks.length-failed.length}/${checks.length} passed`)
if(failed.length){process.exitCode=1}
