import fs from 'node:fs'
import path from 'node:path'
const root=process.cwd()
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8')
const css=fs.readFileSync(path.join(root,'src/App.css'),'utf8')
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'))
const checks=[]
const check=(name,ok,detail='')=>checks.push({name,ok:Boolean(ok),detail})

check('Release is v0.16',pkg.version==='0.16.0',pkg.version)
check('Landing uses creation-first hero',app.includes('hero-creative-studio')&&app.includes('Start with a template'))
check('Landing no longer exposes Explore CMS CTA',!app.slice(app.indexOf('function LandingPage'),app.indexOf('function Auth')).includes('Explore CMS'))
check('Landing inspiration rail exists',app.includes('DESIGN INSPIRATION')&&app.includes('inspiration-rail'))
check('Landing creation workflow section exists',app.includes('CREATE VISUALLY')&&app.includes('Direct visual editing'))
check('Landing public empty article copy is customer-facing',app.includes('Wedding journal segera hadir'))
check('Public root is no longer min-width 1080',css.includes('html,body,#root{min-width:0!important}'))
check('Responsive landing media query exists',css.includes('@media(max-width:560px)')&&css.includes('.landing-v015'))
check('Reduced motion support exists',css.includes('@media (prefers-reduced-motion: reduce)'))

check('Website design preview accepts saved sections',app.includes('WebsiteTemplatePreview({template,title,sections}')&&app.includes('actual-preview-section'))
check('Website design preview passes design.sections',app.includes('sections={design.sections}'))
check('Actual preview renders actual Canvas 01 data',app.includes('const section=sections[0]')&&app.includes('actual-preview-cover-content'))
check('Template preview no longer uses sectionCount prop',!app.includes('sectionCount={design.sections.length}'))

check('Feature object alignment type exists',app.includes("type FeatureObjectAlign = 'left' | 'center' | 'right' | 'stretch'"))
check('Feature object width exists',app.includes('objectWidth?: number'))
check('Inspector has Feature Layout controls',app.includes('Feature Layout')&&app.includes('Feature alignment'))
check('Object align buttons cover left/center/right/stretch',app.includes("['left',AlignLeft]")&&app.includes("['right',AlignRight]")&&app.includes("['stretch',AlignJustify]"))
check('FeatureBlock applies object style',app.includes('getFeatureObjectStyle(feature)'))
check('Canvas column is flex for alignSelf',css.includes('.canvas-column{display:flex;flex-direction:column;align-items:stretch}'))
check('Feature library search exists',app.includes('Cari feature...')&&app.includes('widgetQuery'))
check('Feature duplicate action exists',app.includes('duplicateFeature')&&app.includes('Duplicate feature'))

check('Greetings receives feature style context',app.includes('<GreetingsWidget feature={feature}'))
check('Greetings gradient surface class exists',app.includes("feature?.backgroundGradientEnabled?'gradient-active':''"))
check('Greetings gradient CSS uses translucent inner surfaces',css.includes('.greetings-widget.gradient-active form')&&css.includes('rgba(255,255,255,.18)'))
check('Greetings alignment variants exist',css.includes('.greetings-widget.align-center')&&css.includes('.greetings-widget.align-right'))
check('Greetings empty state exists',app.includes('Belum ada ucapan. Jadilah yang pertama.'))

check('Cover icon is configurable',app.includes('coverIcon?: CoverIconName')&&app.includes('Opening Icon'))
check('Cover icon choices include mail/heart/sparkles/crown/calendar/none',app.includes('<option value="heart">Heart</option>')&&app.includes('<option value="none">No icon</option>'))
check('Cover button radius configurable',app.includes('coverButtonRadius?: number')&&app.includes('Button radius'))
check('Cover button border configurable',app.includes('coverButtonBorderWidth?: number')&&app.includes('Border width'))
check('Cover button background configurable',app.includes('coverButtonBackground?: string')&&app.includes('Button color'))
check('Cover content alignment applies whole flex content',app.includes('alignItems:getCoverContentAlignment(active.align)'))
check('Cover vertical alignment configurable',app.includes('coverVerticalAlign')&&app.includes('Vertical position'))
check('Cover uses feature gradient in editor',app.includes('cover-feature-editor" style={{background:getGradientBackground(feature.backgroundGradientEnabled'))
check('Cover uses feature gradient in public renderer',app.includes('invitation-cover-column" key={column.id} style={active?{background:getGradientBackground(active.backgroundGradientEnabled'))
check('Cover default CSS no longer references cover-reference',!css.slice(css.indexOf('.invitation-cover-screen'),css.indexOf('.invitation-cover-screen')+500).includes('cover-reference.png'))
check('Cover opening selector includes slide up/down',app.includes('<option value="slide-up">Slide Up</option>')&&app.includes('<option value="slide-down">Slide Down</option>'))
check('Cover opening selector includes directional/zoom/curtain/split/dissolve',app.includes('Slide Left')&&app.includes('Slide Right')&&app.includes('Curtain')&&app.includes('Split Reveal')&&app.includes('Dissolve'))
check('Cover exit duration is configurable',app.includes('coverExitDuration')&&app.includes('Duration <span>'))
check('Cover exit easing is configurable',app.includes('coverExitEasing')&&app.includes('Ease In Out'))
check('WeddingCanvas uses configured opening duration',app.includes('Math.max(150, coverEntry.feature.coverExitDuration ?? 700)'))
check('Opening effect CSS keyframes exist',css.includes('coverV15SlideUp')&&css.includes('coverV15SlideDown')&&css.includes('coverV15Curtain')&&css.includes('coverV15Dissolve'))
check('Opening loading overlay no longer hides transition',!app.slice(app.indexOf('function InvitationCover'),app.indexOf('function FeatureBlock')).includes('cover-loading'))

check('Fixed sound player maps object alignment to position',app.includes('sound-pos-${feature.objectAlign')&&css.includes('.fixed-sound-disc.sound-pos-right'))
check('Form content alignment uses feature align',app.includes('className="canvas-form" style={{textAlign:feature.align}}'))

const failed=checks.filter(item=>!item.ok)
for(const item of checks) console.log(`${item.ok?'PASS':'FAIL'} ${item.name}${item.detail?` — ${item.detail}`:''}`)
console.log(`\nUX QA v0.16: ${checks.length-failed.length}/${checks.length} passed`)
if(failed.length) process.exit(1)
